abbr md "mkdir"
abbr rd "rmdir"
abbr groh "git reset origin/(__git.current_branch) --hard"
abbr jab "jj abandon"
abbr je "jj edit"
abbr jst "jj st"
abbr jsp "jj split -i"
abbr jd "jj diff"
abbr jdm "jj diff --from (__git.default_branch)"
abbr jf "jj git fetch"
abbr jfa "jj git fetch --all-remotes"
abbr jp "jj git push"
abbr jpa "jj git push --all"
abbr jpan "jj git push --allow-new"
abbr jn "jj new"
abbr jc "jj describe"
abbr jsh "jj show"
abbr jb "jj bookmark"
abbr jbc "jj bookmark create"
abbr jbd "jj bookmark delete"
abbr jbl "jj bookmark list"
abbr jba "jj bookmark list --all"
abbr jbt "jj bookmark track"
abbr jbm "jj bookmark move"
abbr jrb "jj rebase"
abbr jdu "jj duplicate"
abbr jsq "jj squash"
abbr jlm "jj log -r ::(__git.default_branch)"
abbr jla "jj log -r 'all()'"
abbr jt "jj tag list"
abbr jcl "jj git clone --colocate"
