abbr md "mkdir"
abbr rd "rmdir"
abbr groh "git reset origin/(__git.current_branch) --hard"
abbr jab "jj abandon"
abbr je "jj edit"
abbr jst "jj st"
abbr jsp "jj split -i"
abbr jd "jj diff"
abbr jf "jj git fetch"
abbr jp "jj git push"
abbr jn "jj new"
abbr jc "jj describe"
abbr jsh "jj show"
abbr jb "jj bookmark list"
abbr jba "jj bookmark list --all"
abbr jbt "jj bookmark track"
abbr jbm "jj bookmark move"
abbr jrb "jj rebase"
abbr jdu "jj duplicate"
abbr jsq "jj squash"
abbr jlm "jj log -r ::(__git.default_branch)"
abbr jt "jj tag list"
