"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "John M Daly"
email = "jmdaly@gmail.com"

[ui]
default-command = "log"
diff.tool = ["difft", "--color=always", "$left", "$right"]
