"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "John M Daly"
email = "jmdaly@gmail.com"

[ui]
default-command = "log"
diff.tool = ["difft", "--color=always", "$left", "$right"]

[merge-tools.mergiraf]
program = "mergiraf"
merge-args = ["merge", "$base", "$left", "$right", "-o", "$output", "--fast"]
merge-conflict-exit-codes = [1]
conflict-marker-style = "git"
