"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "John M Daly"
email = "jmdaly@gmail.com"

[ui]
default-command = "log"
diff.tool = ["difft", "--color=always", "$left", "$right"]

[git]
private-commits = '''description(glob:'private:*')'''

[[--scope]]
--when.repositories = ["/workspaces", "~/workspaces"]
[--scope.user]
name = "John Daly"
email = "john.daly@ouster.io"
