[user]
	email = mruss100@ford.com
	signingkey = DE8210182994327F
[http]
	cookiefile = ~/dotfiles/dotfiles-secret/ford/gitcookies
[url "https://github.ford.com"]
	insteadOf = ssh://github.ford.com
[url "https://gist.github.ford.com"]
	insteadOf = ssh://gist.github.ford.com

[url "file:///opt/phoenix/PHX-Codeaurora-LA.AU.0.3.1.r4-03800-plus-widevine-and-vms/"]
	insteadOf = ssh://gerrit.ford.com:29418/CODEAURORA/quic/la/
	insteadOf = ssh://gerrit.ford.com:29418/AOSP/

; vim: ft=gitconfig :
