- name: openai/gemini-2.5-pro
  edit_format: diff-fenced
  weak_model_name: openai/gemini-2.0-flash-001
  use_repo_map: true
  overeager: true

- name: openai/claude-3.7-sonnet
  edit_format: diff
  weak_model_name: openai/gemini-2.0-flash-001
  use_repo_map: true
  overeager: true
  examples_as_sys_msg: true
  editor_model_name: openai/claude-3.7-sonnet
  editor_edit_format: editor-diff
